spring.application.name=ems
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=8431362872
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
logging.level.com.example.ems=DEBUG
